- name: Deploy Postgresql.conf templated file
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/9.6/data/postgresql.conf
    mode: '0644'

- name: Create archive directory
  file:
    path: /var/lib/pgsql/9.6/archive
    mode: 0700
    owner: postgres
    group: postgres
    state: directory

- name: Deploy pg_hba.conf
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    mode: '0644'
  notify: restart postgresql-9.6

- name: Create replication user
  shell: sudo -u postgres psql -c "CREATE USER replica REPLICATION LOGIN ENCRYPTED PASSWORD '{{ postgresdb_replica_password }}'"

- name: Create postgres user for odoo
  shell: sudo -u postgres psql -c "create user {{ postgresdb_odoo_user }} with encrypted password '{{ postgres_odoouser_pass }}'"

- name: Allow role
  shell: sudo -u postgres psql -c "alter user {{ postgresdb_odoo_user }} createdb"

- name: Create DB for odoo
  shell: sudo -u postgres psql -c "create database {{ postgresdb_odoo_db }}"

- name: Grant user access on odoo db
  shell: sudo -u postgres psql -c "grant all privileges on database {{ postgresdb_odoo_db }} to {{ postgresdb_odoo_user }}"
