- name: Postgres DB common setup
  hosts: postgresdb
  gather_facts: yes
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - postgres_common

- name: Postgres DB master setup
  hosts: postgres1
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - postgres_master

- name: Postgres DB slave setup
  hosts: postgres2
  become: yes
  become_method: sudo
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - postgres_slave

- name: Odoo servers setup in a Docker container
  hosts: odoo
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: odoo_setup, become: yes, decome_method: sudo }

- name: Setup nginx server and configure as reverse proxy
  hosts: nginx
  gather_facts: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: nginx_setup, become: yes, become_method: sudo } 
